name: t20_worldcup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  connectivity_plus: ^2.2.1
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter_native_splash:
  background_image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/data/ttwenty.json
    - assets/flags/
    - assets/venues/dubai.jpeg
    - assets/venues/oman.jpeg
    - assets/venues/sharjah.jpeg
    - assets/venues/sz.jpeg
